### ISSUE TITLE
Docs example mix-up:: New-MgDirectoryRoleTemplate cmdlet

### ISSUE THREAD

**Issue by SteveMutungi254** [MicrosoftDocs/microsoftgraph-docs-powershell#397]
The cmdlet [New-MgDirectoryRoleTemplate](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/new-mgdirectoryroletemplate?view=graph-powershell-1.0&preserve-view=true) shows an example with a Get operation.

**Snippet:**

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/132555836/92d1f791-d17f-4c9e-9c51-7eac7ff4108e)

**Call to action:**

Correct this example and others like these in bulk.

**Comment by msewaweru** [comment]
We even don't seem to have a Create API for the Directory role template which means the cmdlet should also not exist. This could be a manifestation of the overgeneration issue caused by last of annotations in the schema.
<img width="326" alt="image" src="https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/73849846/f1a91437-b911-46bd-a523-6d3c50e6409e">
