### ISSUE TITLE
Get-MgDeviceManagementManagedDevice Blank HardwareInformation

### ISSUE THREAD

**Issue by erentz71** [MicrosoftDocs/microsoftgraph-docs-powershell#435]
I don't see the HardwareInformation field.  It is available in Get-MgBetaDeviceManagementManagedDevice.  With Get-MgBetaDeviceManagementManagedDevice it is only available when supplying a single ManagedDeviceId.  It returns blank information when calling with a filter or just calling.

The following returns blank information for HardwareInventory.
Get-MgbetaDeviceManagementManagedDevice -select devicename,id,LastSyncDateTime,hardwareinformation -Filter "operatingsystem eq 'Windows'"

The following does not work for me.
Get-MgDeviceManagementManagedDevice -select devicename,id,LastSyncDateTime,hardwareinformation -Filter "operatingsystem eq 'Windows'"

I have a need to report out the wiredIPV4Address for Intune managed devices.  Having to call each one individually is quite slow.

Any advice or assistance would be appreciated.

**Comment by timayabi2020** [comment]
Hi @erentz71 apologies for the super delay in giving feedback.
That property is no longer being supported by the API owner. You can see the list of supported properties [here](https://learn.microsoft.com/en-us/graph/api/resources/intune-devices-manageddevice?view=graph-rest-1.0).
For API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
