### ISSUE TITLE
Version selector note missing - New-MgGroupMember

### ISSUE THREAD

**Issue by SteveMutungi254** [MicrosoftDocs/microsoftgraph-docs-powershell#466]
The version selector for the command `New-MgGroupMember` is missing.

Sample Cmdlets:
[New-MgGroupMember](https://learn.microsoft.com/en-au/powershell/module/microsoft.graph.groups/new-mggroupmember)

Note: Not very common though.

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/132555836/d1258722-c1b0-40b6-b13e-ca2ba29ccee5)

**Expectation:**

![image](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/assets/132555836/620b5d89-1f48-47ef-a985-137c1c8529ce)

**Comment by msewaweru** [comment]
Hi @SteveMutungi254 - due to the planned migration from GitHub issues to UUF, we are in the process of closing all open GH issues. For those that we would like to follow up in future, we'll create ADO work items to track them and close the GH issue.
Since this issue is still open, could you open a work item to Timothy?

**Comment by msewaweru** [comment]
ADO work item created to track this.

[259508](https://dev.azure.com/msft-skilling/Content/_workitems/edit/259508/?view=edit)	User Story	[Issue]Version selector note missing - New-MgGroupMember	Eunice Waweru <eunicewaweru@microsoft.com>	New
