### ISSUE TITLE
How to install Microsoft Graph off line with PowerShell?

### ISSUE THREAD

**Issue by fredatgithub** [MicrosoftDocs/microsoftgraph-docs-powershell#499]
[I followed the installation procedure to install Microsoft Graph with PowerShell commands]
https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0
but I have an off line server with no access to Internet.
How and where do I download the PowerShell Graph Module?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfa0d6a2-8795-2d70-8282-4ab8169c8b70
* Version Independent ID: 80d8d30e-9bc3-87c1-1f8f-70850a787b3c
* Content: [Install the Microsoft Graph PowerShell SDK](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0)
* Content Source: [microsoftgraph/docs-conceptual/installation.md](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/blob/live/microsoftgraph/docs-conceptual/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph-powershell**
* GitHub Login: @msewaweru
* Microsoft Alias: **eunicewaweru**

**Comment by fredatgithub** [comment]
I have found this information:
https://www.manishbangia.com/install-powershell-module-offline/
I have tried to install Microsof Graph with the command:
Import-Module -Name Microsoft.Graph
and I got the following error :

PS C:\Users\username> Import-Module -Name Microsoft.Graph
Import-Module : Function Get-MgEntitlementManagementResourceRoleScopeRoleResourceScope cannot be created because
function capacity 4096 has been exceeded for this scope.
At line:1 char:1
+ Import-Module -Name Microsoft.Graph
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Get-MgEntitleme...leResourceScope:String) [Import-Module], SessionSta
   teOverflowException
    + FullyQualifiedErrorId : FunctionOverflow,Microsoft.PowerShell.Commands.ImportModuleCommand

PS C:\Users\username>

**Comment by csmulligan** [comment]
Thanks @fredatgithub for highlighting the issue.
Adding @timayabi2020 @peombwa @CarolKigoonya for review.

**Comment by csmulligan** [comment]
Hi @fredatgithub thanks for reaching out and looking for a workaround. Since this issue isn’t directly related to our docs, and to gain a better understanding of your issue, I’d recommend working closer with our product support team and open an issue [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues). Or you can leverage our Q&A community and ask the question [here](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph). 
I’ll go ahead and close this issue for now, but please don’t hesitate to reach out if you require any further assistance.
Thanks again!

**Comment by fredatgithub** [comment]
OK thanks
