### ISSUE TITLE
Why isn't this human readable?

### ISSUE THREAD

**Issue by SeanMurphy-CDW** [MicrosoftDocs/microsoftgraph-docs-powershell#508]
I wish the cmdlets used / read human readable values. ID numbers aren't easy to use for anything except API's. If you've got ten's of roles / groups that you manage under PIM it'd be great to see human values for applying eligible/active permissions to PIM.

**Comment by csmulligan** [comment]
Hi @SeanMurphy-CDW thanks for reaching out. It can be challenging to follow up with all the ID numbers indeed. In some scenarios, you can specify filters to use the DisplayName of the specific group. As an example, when using the `Get-MgGroup` cmdlet:

`Get-MgGroup -Filter "DisplayName eq 'GroupName'"`

For more details about this specific cmdlet, please see the documentation [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroup?view=graph-powershell-1.0).

Since this issue isn’t directly related to improving our docs, and to gain a better understanding of your feedback, I’d recommend working closer with our product support team and opening an issue [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues).

I’ll go ahead and close this issue for now, but please don’t hesitate to reach out if you require any further assistance.
Thanks again!
