### ISSUE TITLE
Microsoft.Graph.WindowsUpdates missing the module file in the folder

### ISSUE THREAD

**Issue by xmdanni** [MicrosoftDocs/microsoftgraph-docs-powershell#62]
https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/tree/live/microsoftgraph/graph-powershell-beta/Microsoft.Graph.WindowsUpdates

There is no module_name.md file in this folder.

**Comment by maisarissi** [comment]
Update: After our last sync, @timayabi2020 was going to investigate whether AutoREST is responsible for creating the module_name.md file and if that's related to the missing online documentation.

**Comment by timayabi2020** [comment]
@maisarissi the cmdlets exist on the WindowsUpdates node. Check [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.windowsupdates/add-mgwindowsupdatesdeploymentaudienceexclusionmemberbyid?view=graph-powershell-beta).
I think this scenario occurred when I was still using my local machine for copying files from the powershell sdk repo to microsoftgraph-docs-powershell repo. My suspicion is that due to the resource constraints the process might have deleted and missed replacing them in that node. Now that we have this process on a pipeline, I hope we won't have this issue again.

**Comment by maisarissi** [comment]
@msewaweru I don't have permission to close the issue, but this is now fixed by having a docs generation pipeline.

**Comment by timayabi2020** [comment]
@msewaweru [check here](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.windowsupdates/?view=graph-powershell-beta)

**Comment by msewaweru** [comment]
@xmdanni - thanks for bringing this issue to our attention. This has been resolved.
